services:
  mariadb:
    build: ./mariadb
    restart: always
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - app-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env
    networks:
      - app-net

  wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mal-mora/docker-volumes/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mal-mora/docker-volumes/wordpress
